import { roadSegments as demoRoads, cameras as demoCameras } from './data.js?v=%%VERSION%%';
import { loadNearbyOsm, osmCache } from './osm.js?v=%%VERSION%%';

const $=id=>document.getElementById(id); const ui={speed:$('speedValue'),limit:$('limitBadge'),speedCard:document.querySelector('.speed-card'),cameraCard:$('cameraCard'),cameraTitle:$('cameraTitle'),cameraDistance:$('cameraDistance'),gpsState:$('gpsState'),heading:$('headingValue'),accuracy:$('accuracyValue'),dataState:$('dataState'),start:$('startButton'),demo:$('demoButton'),sound:$('soundButton'),status:$('statusText')};
let watchId=null,soundEnabled=true,demoTimer=null,previousPosition=null,demoMode=false; const lastSpoken=new Map();
ui.dataState.textContent='OSM live';
const rad=v=>v*Math.PI/180,deg=v=>v*180/Math.PI;
function distance(a,b){const R=6371000,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),p1=rad(a.lat),p2=rad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function bearing(a,b){const p1=rad(a.lat),p2=rad(b.lat),d=rad(b.lng-a.lng),y=Math.sin(d)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(d);return(deg(Math.atan2(y,x))+360)%360;}
const angleDiff=(a,b)=>Math.abs(((a-b+540)%360)-180);
function pointToSegment(p,a,b){const x=p.lng,y=p.lat,x1=a.lng,y1=a.lat,x2=b.lng,y2=b.lat,dx=x2-x1,dy=y2-y1;if(!dx&&!dy)return distance(p,a);const t=Math.max(0,Math.min(1,((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy)));return distance(p,{lat:y1+t*dy,lng:x1+t*dx});}
function roadDistance(pos,r){if(r.geometry?.length>1){let best=Infinity;for(let i=1;i<r.geometry.length;i++)best=Math.min(best,pointToSegment(pos,r.geometry[i-1],r.geometry[i]));return best;}return distance(pos,r);}
function datasets(){const c=osmCache();return demoMode?{roads:demoRoads,cameras:demoCameras}:{roads:c.roads,cameras:c.cameras};}
function currentRoad(pos){return datasets().roads.map(r=>({...r,distance:roadDistance(pos,r)})).filter(r=>r.distance<=(r.radiusMeters||120)).sort((a,b)=>a.distance-b.distance)[0]||null;}
function cameraAhead(pos,heading){return datasets().cameras.map(c=>({...c,distance:distance(pos,c),toward:heading==null||angleDiff(bearing(pos,c),heading)<=55,facing:c.direction==null||heading==null||angleDiff(c.direction,heading)<=70})).filter(c=>c.distance<=1500&&c.toward&&c.facing).sort((a,b)=>a.distance-b.distance)[0]||null;}
function speak(key,text,cooldown=20000){if(!soundEnabled||!('speechSynthesis'in window))return;const now=Date.now();if(now-(lastSpoken.get(key)||0)<cooldown)return;lastSpoken.set(key,now);speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='vi-VN';u.rate=1.05;speechSynthesis.speak(u);}
function render({lat,lng,speedKmh,heading,accuracy}){const pos={lat,lng},road=currentRoad(pos),camera=cameraAhead(pos,heading),limit=road?.speedLimit??camera?.speedLimit??null;ui.speed.textContent=Number.isFinite(speedKmh)?Math.max(0,Math.round(speedKmh)):'--';ui.limit.textContent=limit??'--';ui.heading.textContent=Number.isFinite(heading)?`${Math.round(heading)}°`:'--°';ui.accuracy.textContent=Number.isFinite(accuracy)?`${Math.round(accuracy)} m`:'-- m';const over=limit&&Number.isFinite(speedKmh)&&speedKmh>=limit+3;ui.speedCard.classList.toggle('over-limit',!!over);if(over)speak('speed',`Bạn đang vượt tốc độ. Giới hạn ${limit} ki lô mét một giờ.`,12000);if(camera){const m=Math.round(camera.distance/10)*10,label=camera.type==='red_light'?'Camera đèn đỏ phía trước':'Camera tốc độ phía trước';ui.cameraTitle.textContent=label;ui.cameraDistance.textContent=`${m} m`;ui.cameraCard.classList.add('near');if(m<=1000)speak(`cam-${camera.id}-1000`,`${label}, khoảng ${m} mét.`,60000);if(m<=400)speak(`cam-${camera.id}-400`,`${label}, còn khoảng ${m} mét.`,60000);}else{ui.cameraTitle.textContent='Không có camera gần';ui.cameraDistance.textContent='--';ui.cameraCard.classList.remove('near');}ui.status.textContent=road?`${road.name} · ${road.source||'demo'}`:(demoMode?'Demo':'Đang theo dõi GPS');}
async function handlePosition(p){const c=p.coords,sGps=Number.isFinite(c.speed)&&c.speed>=0?c.speed*3.6:null;let heading=Number.isFinite(c.heading)?c.heading:null,speedKmh=sGps;if(previousPosition){const dt=(p.timestamp-previousPosition.timestamp)/1000,prev=previousPosition.coords,dist=distance({lat:prev.latitude,lng:prev.longitude},{lat:c.latitude,lng:c.longitude});if(heading==null&&dist>=4)heading=bearing({lat:prev.latitude,lng:prev.longitude},{lat:c.latitude,lng:c.longitude});if(speedKmh==null&&dt>0&&dt<=15)speedKmh=dist/dt*3.6;}previousPosition=p;ui.gpsState.textContent='Hoạt động';try{const d=await loadNearbyOsm(c.latitude,c.longitude);ui.dataState.textContent=`OSM ${d.roads.length} đường · ${d.cameras.length} cam`;}catch{ui.dataState.textContent='OSM cache';}render({lat:c.latitude,lng:c.longitude,speedKmh,heading,accuracy:c.accuracy});}
function startGps(){stopDemo();demoMode=false;if(!navigator.geolocation){ui.gpsState.textContent='Không hỗ trợ';return;}if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null;ui.start.textContent='Bắt đầu cảnh báo';ui.gpsState.textContent='Đã dừng';return;}ui.status.textContent='Đang xin quyền GPS…';watchId=navigator.geolocation.watchPosition(handlePosition,e=>{ui.gpsState.textContent='Lỗi';ui.status.textContent=e.code===1?'Bạn chưa cho phép truy cập vị trí':'Không lấy được GPS';},{enableHighAccuracy:true,maximumAge:1000,timeout:12000});ui.start.textContent='Dừng cảnh báo';}
function stopDemo(){if(demoTimer)clearInterval(demoTimer);demoTimer=null;demoMode=false;ui.demo.textContent='Chạy chế độ demo';}
function startDemo(){if(demoTimer){stopDemo();return;}if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null;ui.start.textContent='Bắt đầu cảnh báo';}demoMode=true;let i=0;ui.gpsState.textContent='Demo';ui.dataState.textContent='Demo data';ui.demo.textContent='Dừng demo';const tick=()=>{const t=i++/18;render({lat:10.775+t*.005,lng:106.699+t*.010,speedKmh:42+Math.sin(t*Math.PI)*24,heading:55,accuracy:8});if(t>=1)i=0;};tick();demoTimer=setInterval(tick,1000);}
ui.start.addEventListener('click',startGps);ui.demo.addEventListener('click',startDemo);ui.sound.addEventListener('click',()=>{soundEnabled=!soundEnabled;ui.sound.textContent=soundEnabled?'🔊':'🔇';if(!soundEnabled&&'speechSynthesis'in window)speechSynthesis.cancel();});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
